### ISSUE TITLE
ImageSharp.Image frames count is always 1

### ISSUE THREAD

**Issue by sergiuciudin** [yigolden/TiffLibrary#11] opened 2021-11-25 10:41 UTC
Trying to get frames from a tiff with multiple images but count is always 1 so i can get only first image.

`
using MemoryStream inputStream = new MemoryStream(bytes);
using var tiff = Image.Load(inputStream);
tiff.Frames.Count // returns 1
`

**Comment by MM-YJN** [comment] 2021-11-26 01:24
Duplicate of #3 

> I don't think this is possible with the Image.Frames API. Because in ImageSharp, frames in an image must have the same size. They are exclusively used in GIF format. While in multipage TIFF, pages can have different sizes. They should be treated like a collection of images instead of frames.

However, you can use the following code to enumerate the pages and process them using ImageSharp API.

```csharp
using TiffFileReader reader = await TiffFileReader.OpenAsync(inputStream, leaveOpen: true);
TiffStreamOffset ifdOffset = reader.FirstImageFileDirectoryOffset;
int index = 0;
while (!ifdOffset.IsZero)
{
    TiffImageFileDirectory ifd = await reader.ReadImageFileDirectoryAsync(ifdOffset);
    TiffImageDecoder decoder = await reader.CreateImageDecoderAsync(ifd);
    Image<Rgba32> image = new Image<Rgba32>(decoder.Width, decoder.Height);
    await decoder.DecodeAsync(image);
    await image.SaveAsPngAsync(@$"C:\Test\{++index}.png");
    ifdOffset = ifd.NextOffset;
}
```

**Closed as completed by MM-YJN** 2021-11-26 01:24 UTC
